const mongoose = require("mongoose");

const subscriptionBookingSchema = new mongoose.Schema(
  {
    subscription: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Subscription",
      required: true,
      index: true,
    },
    schedule: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "SubscriptionSchedule",
      default: null,
    },
    booking: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Booking",
      required: true,
      index: true,
    },
    cycleIndex: {
      type: Number,
      required: true,
      min: 0,
    },
    sessionNumber: {
      type: Number,
      required: true,
      min: 1,
    },
    status: {
      type: String,
      enum: ["DRAFT", "CONFIRMED", "COMPLETED", "CANCELLED", "RESCHEDULED", "NEED_RESCHEDULE"],
      default: "DRAFT",
      index: true,
    },
    scheduledStart: {
      type: Date,
      required: true,
    },
    scheduledEnd: {
      type: Date,
      required: true,
    },
    conflictReason: {
      type: String,
      default: "",
    },
    rescheduleRequired: {
      type: Boolean,
      default: false,
    },
    suggestedSlots: {
      type: [mongoose.Schema.Types.Mixed],
      default: [],
    },
    isAutoGenerated: {
      type: Boolean,
      default: true,
    },
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
  },
  {
    timestamps: true,
    collection: "subscriptionBookings",
  }
);

subscriptionBookingSchema.index({ subscription: 1, cycleIndex: 1, sessionNumber: 1 }, { unique: true });

module.exports = mongoose.models.SubscriptionBooking || mongoose.model("SubscriptionBooking", subscriptionBookingSchema);
